<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class TausuarioSeeder extends Seeder{
	public function run(){
		$data =[
			[
				'FCNOMBREUSUARIO' => 'Rogelio',
				'FCAPELLIDOPATERNO' => 'Espinosa',
				'FCAPELLIDOMATERNO' => 'Reyes',
				'FCEMAIL' => 'respinosa@koomersys.com',
				'FCCLAVE' => '$2y$10$XKbmag11EnmfwV3nq2e6eukIQF.atG0Hj6gvSOkfpDI4nOHmeVpea',
				'FIROLID' => 1,
				'FISUCURSALID' => 1,
				'FIESTATUS' => 1,
				'FIEMAILVERIFICADO' => 1,
				'FDFECHAALTA' => '2025-07-11 00:00:00',
				'FDFECHAACTUALIZACION' => '2025-07-11 00:00:00',
				'FCRECORDARTOKEN' => null,
				'FDRECORDARTOKENFIN' => null
			],
			[
				'FCNOMBREUSUARIO' => 'Paulina Mayte',
				'FCAPELLIDOPATERNO' => 'Sanchez',
				'FCAPELLIDOMATERNO' => 'Vega',
				'FCEMAIL' => 'pmsanchez@koomersys.com',
				'FCCLAVE' => '$2y$10$hcs863LVbkVYXoX375gZjuyo5i8FZaw5KtK6GONR1HyjQ4X9LjdMm',
				'FIROLID' => 1,
				'FISUCURSALID' => 2,
				'FIESTATUS' => 1,
				'FIEMAILVERIFICADO' => 1,
				'FDFECHAALTA' => '2025-07-11 00:00:00',
				'FDFECHAACTUALIZACION' => '2025-07-11 00:00:00',
				'FCRECORDARTOKEN' => null,
				'FDRECORDARTOKENFIN' => null
			],
			[
				'FCNOMBREUSUARIO' => 'Damaris',
				'FCAPELLIDOPATERNO' => 'Espinosa',
				'FCAPELLIDOMATERNO' => 'Chiquini',
				'FCEMAIL' => 'despinosa@koomersys.com',
				'FCCLAVE' => '$2y$10$I7xeIuyC/1zv4o31yM6tmeh08UdlzHTgA.rwRMYWihat7Hz.6jC/S',
				'FIROLID' => 1,
				'FISUCURSALID' => 3,
				'FIESTATUS' => 1,
				'FIEMAILVERIFICADO' => 1,
				'FDFECHAALTA' => '2025-07-11 00:00:00',
				'FDFECHAACTUALIZACION' => '2025-07-11 00:00:00',
				'FCRECORDARTOKEN' => null,
				'FDRECORDARTOKENFIN' => null
			],
			[
				'FCNOMBREUSUARIO' => 'Isaac',
				'FCAPELLIDOPATERNO' => 'Espinoza',
				'FCAPELLIDOMATERNO' => 'Reyes',
				'FCEMAIL' => 'iespinosa@koomersys.com',
				'FCCLAVE' => '$2y$10$HguQBm74etTiilj7czji4u55UNne1b7RNiF0SHh1mXZyqWZKS65qy',
				'FIROLID' => 1,
				'FISUCURSALID' => 4,
				'FIESTATUS' => 1,
				'FIEMAILVERIFICADO' => 1,
				'FDFECHAALTA' => '2025-07-11 00:00:00',
				'FDFECHAACTUALIZACION' => '2025-07-11 00:00:00',
				'FCRECORDARTOKEN' => null,
				'FDRECORDARTOKENFIN' => null
				],
				[
					'FCNOMBREUSUARIO' => 'Rogelio',
					'FCAPELLIDOPATERNO' => 'Espnosa',
					'FCAPELLIDOMATERNO' => 'Rosales',
					'FCEMAIL' => 'rerosales@koomersys.com',
					'FCCLAVE' => '$2y$10$fGBSodxS1/QaOfSBWcP/2.MeM/cXNrW4gXbtnf8BeYk/iom9ID2o.',
					'FIROLID' => 1,
					'FISUCURSALID' => 5,
					'FIESTATUS' => 1,
					'FIEMAILVERIFICADO' => 1,
					'FDFECHAALTA' => '2025-07-11 00:00:00',
					'FDFECHAACTUALIZACION' => '2025-07-11 00:00:00',
					'FCRECORDARTOKEN' => null,
					'FDRECORDARTOKENFIN' => null
				],
				[
					'FCNOMBREUSUARIO' => 'Efrain',
					'FCAPELLIDOPATERNO' => 'Espinoza',
					'FCAPELLIDOMATERNO' => 'Rosales',
					'FCEMAIL' => 'eespinosa@koomersys.com',
					'FCCLAVE' => '$2y$10$O.5bzT1nwH52e6CshPSGE.MoVtQ5yA/hnhwMBcs7OAxloCTBoA8ZK',
					'FIROLID' => 1,
					'FISUCURSALID' => 1,
					'FIESTATUS' => 1,
					'FIEMAILVERIFICADO' => 1,
					'FDFECHAALTA' => '2025-07-11 00:00:00',
					'FDFECHAACTUALIZACION' => '2025-07-11 00:00:00',
					'FCRECORDARTOKEN' => null,
					'FDRECORDARTOKENFIN' => null
				],
				[
					'FCNOMBREUSUARIO' => 'Cruz Adrian',
					'FCAPELLIDOPATERNO' => 'Espinosa',
					'FCAPELLIDOMATERNO' => 'Ruiz',
					'FCEMAIL' => 'caespinosa@koomersys.com',
					'FCCLAVE' => '$2y$10$UV0gE3OeAQJQIKQLW0tdA.1gDBNfzFNXFSE4GU2KoeycFryVVr2D.',
					'FIROLID' => 1,
					'FISUCURSALID' => 2,
					'FIESTATUS' => 1,
					'FIEMAILVERIFICADO' => 1,
					'FDFECHAALTA' => '2025-07-11 00:00:00',
					'FDFECHAACTUALIZACION' => '2025-07-11 00:00:00',
					'FCRECORDARTOKEN' => null,
					'FDRECORDARTOKENFIN' => null
				],
				[
					'FCNOMBREUSUARIO' => 'Jose Cruz',
					'FCAPELLIDOPATERNO' => 'Espinosa',
					'FCAPELLIDOMATERNO' => 'Rosales',
					'FCEMAIL' => 'jcespinosa@koomersys.com',
					'FCCLAVE' => '$2y$10$Qat.RGCc7CsInV0bMahd7OXjy9k7j2s8.FPrDaArsycU0CD0ixLNa',
					'FIROLID' => 1,
					'FISUCURSALID' => 3,
					'FIESTATUS' => 1,
					'FIEMAILVERIFICADO' => 1,
					'FDFECHAALTA' => '2025-07-11 00:00:00',
					'FDFECHAACTUALIZACION' => '2025-07-11 00:00:00',
					'FCRECORDARTOKEN' => null,
					'FDRECORDARTOKENFIN' => null
				],
				[
					'FCNOMBREUSUARIO' => 'Marbella',
					'FCAPELLIDOPATERNO' => 'Ruiz',
					'FCAPELLIDOMATERNO' => '-',
					'FCEMAIL' => 'mruiz@koomersys.com',
					'FCCLAVE' => '$2y$10$7K/3Iu87eROUxdPSKqbwGOj5mK8.dhOCYBk8bMdQp43J9xw0g90V.',
					'FIROLID' => 1,
					'FISUCURSALID' => 4,
					'FIESTATUS' => 1,
					'FIEMAILVERIFICADO' => 1,
					'FDFECHAALTA' => '2025-07-11 00:00:00',
					'FDFECHAACTUALIZACION' => '2025-07-11 00:00:00',
					'FCRECORDARTOKEN' => null,
					'FDRECORDARTOKENFIN' => null
				],
				[
					'FCNOMBREUSUARIO' => 'Jhonathan',
					'FCAPELLIDOPATERNO' => 'Vega',
					'FCAPELLIDOMATERNO' => '-',
					'FCEMAIL' => 'jvega@koomersys.com',
					'FCCLAVE' => '$2y$10$xaREN0NbLTFDaUqjOr04qeUpYWaw3i5SVaE.q29DsFRO79URogkte',
					'FIROLID' => 1,
					'FISUCURSALID' => 5,
					'FIESTATUS' => 1,
					'FIEMAILVERIFICADO' => 1,
					'FDFECHAALTA' => '2025-07-11 00:00:00',
					'FDFECHAACTUALIZACION' => '2025-07-11 00:00:00',
					'FCRECORDARTOKEN' => null,
					'FDRECORDARTOKENFIN' => null
				],
				[
					'FCNOMBREUSUARIO' => 'Maria Fernanda',
					'FCAPELLIDOPATERNO' => 'Arredondo',
					'FCAPELLIDOMATERNO' => '-',
					'FCEMAIL' => 'mfarredondo@koomersys.com',
					'FCCLAVE' => '$2y$10$0mapH24chPbGOWZ2do4/lOnYFFoBZpL0A/miKo0jM5wvNx/iOuT66',
					'FIROLID' => 1,
					'FISUCURSALID' => 1,
					'FIESTATUS' => 1,
					'FIEMAILVERIFICADO' => 1,
					'FDFECHAALTA' => '2025-07-11 00:00:00',
					'FDFECHAACTUALIZACION' => '2025-07-11 00:00:00',
					'FCRECORDARTOKEN' => null,
					'FDRECORDARTOKENFIN' => null
				],
				[
					'FCNOMBREUSUARIO' => 'Emily Fernanda',
					'FCAPELLIDOPATERNO' => 'Espinosa',
					'FCAPELLIDOMATERNO' => 'Arredondo',
					'FCEMAIL' => 'efespinosa@koomersys.com',
					'FCCLAVE' => '$2y$10$cS31ROj/2QIrleb/YefqDeVu0szKlziw5vYcg4TQAwDBbFMGLAuCK',
					'FIROLID' => 1,
					'FISUCURSALID' => 2,
					'FIESTATUS' => 1,
					'FIEMAILVERIFICADO' => 1,
					'FDFECHAALTA' => '2025-07-11 00:00:00',
					'FDFECHAACTUALIZACION' => '2025-07-11 00:00:00',
					'FCRECORDARTOKEN' => null,
					'FDRECORDARTOKENFIN' => null
				],
				[
					'FCNOMBREUSUARIO' => 'Berenice',
					'FCAPELLIDOPATERNO' => 'Hernandez',
					'FCAPELLIDOMATERNO' => 'Garcia',
					'FCEMAIL' => 'bhermandez@koomersys.com',
					'FCCLAVE' => '$2y$10$cyrWYOU.Q6BYIEG1bnhnzeuFSwRUaURNMK7mQ6BB2WVAn7/K6jJqa',
					'FIROLID' => 1,
					'FISUCURSALID' => 3,
					'FIESTATUS' => 1,
					'FIEMAILVERIFICADO' => 1,
					'FDFECHAALTA' => '2025-07-11 00:00:00',
					'FDFECHAACTUALIZACION' => '2025-07-11 00:00:00',
					'FCRECORDARTOKEN' => null,
					'FDRECORDARTOKENFIN' => null
				],
				[
					'FCNOMBREUSUARIO' => 'Arlett',
					'FCAPELLIDOPATERNO' => 'Lleraldin',
					'FCAPELLIDOMATERNO' => '-',
					'FCEMAIL' => 'asinapeliido@koomersys.com',
					'FCCLAVE' => '$2y$10$cBudDfqWc.dgvx6rEnK9auflA6vWTey6D45FwD1p2j3xBj4OfZYbm',
					'FIROLID' => 1,
					'FISUCURSALID' => 4,
					'FIESTATUS' => 1,
					'FIEMAILVERIFICADO' => 1,
					'FDFECHAALTA' => '2025-07-11 00:00:00',
					'FDFECHAACTUALIZACION' => '2025-07-11 00:00:00',
					'FCRECORDARTOKEN' => null,
					'FDRECORDARTOKENFIN' => null
			]
		];

		$this->db->table('TAUSUARIO')->insertBatch($data);
	}
}